controller_manager:
  ros__parameters:
    update_rate: 1000  # Increased to match demo
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: forward_command_controller/ForwardCommandController
    

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      # - joint_4  # No need since it is a fixed joint. Uncomment if you the type.
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - joint_5
      # - joint_6  # Add if gripper has a second joint
    interface_name: position
